# -*- coding:utf-8 -*-
#+TITLE:简历
#+AUTHOR:    xxx
#+EMAIL:     xxxx@163.com
#+LANGUAGE:  zh
#+OPTIONS:   toc:nil author:nil creator:nil timestamp:nil

* 个人资料

  - 姓名：xxx
  - 性别：男
  - 电话：xxxxxxxxxx
  - 邮箱：xxxx@163.com
  - 住址：XXXXX

* 应聘职位

  - 高级软件工程师
  - 网络设备管理相关产品的研发职位

* 自我评价
  
  10年大规模（百万行C++代码）软件的开发和维护经验，4年系统工程师经验，
  有带领团队工作和项目管理经验，学习能力强。
  - 精通电信传输网络技术（SDH/MSTP/DWDM/OTN/PTN）
  - 熟悉TCP/IP网络技术
  - 熟练掌握C/C++/Perl/Python
  - 熟练掌握多线程和多进程编程
  - 熟悉solaris平台/window平台/Linux平台开发环境

* 工作经验
** 2009/02 --  至今
   XXX技术有限公司 | 系统工程师
   工作描述：
   电信网络网管软件产品系统工程师/高级工程师，主要负责：

   1. 带领设计团队（2～6人）完成网管软件的系统分析和设计工作
      1) 作为项目负责人的项目管理工作
      2) 作为技术负责人，带领团队从原始需求进行业务需求分析和设计工作
      3) 作为技术负责人，带领团队从业务需求中识别关键技术，并进行备选方
         案的分析和设计
      4) 根据系统分析和设计的输出指导各个开发团队完成各自子系统的分解和
         概详细设计
      5) 从09年担任系统工程师至今累计完成3个项目的系统分析和设计工
	 作，负责系统分析和设计的项目在现网得到大规模应用。

   2. 作为部门网络性能报表的产品的系统工程师，负责新产品的业务需求
      分析和关键技术方案分析，新的报表产品在国内移动集团&省市移动公司以
      及国外运营商完成了部署，新产品的特性获得了客户的极大认可。主要完
      成了：
      1) 传输网络PTN&RTN&OTN&MSTP设备的性能报表的业务需求分析和设计
      2) 网络业务的分析和建模工作，使报表系统更加具备可扩展性。
      3) 提供了高效的采集方案，解决了网络设备性能采集的效率问题。

   3. 作为部门核心骨干，进行关键方案的攻关，提供和解决不限于如下几个关
      键技术问题和方案。
      1) 网管与被管设备之间的IP隧道方案，使被管设备在没有公网IP的情况下，
         也能进行IP化管理，大大简化了应用层代码的适配工作量。
      2) 网管管理的上万套传输网络设备的高效性能采集，解决了困扰传输设备
         网络的性能采集的问题。方案已经在国内和国外多个局点应用，效果良
         好。
      3) 网络大容量性能数据的存储方案。

** 2006/02 -- 2009/01
    XXX技术有限公司 | 软件工程师

    工作描述：作为网管产品数据特性的模块负责人，完成特性模块的概要设计
    和详细设计工作和编码工作，并指导初级软件工程师

    1. 负责数据特性的分析和建模工作，熟悉传输网络业务和二层网络的业务知识。
    2. 主要负责产品服务器端代码（C++）的开发和维护
    3. 使用MS VC和SUN studio工具开发和分析系统效率瓶颈
    4. 使用perl构建测试数据和执行分析

** 2004/02 -- 2006/01
   XXX技术有限工程 | 软件工程师

   工作描述：
   软件工程师主要负责特定模块的开发和维护工作

** 2001/07 -- 2003/12
   XXXXX软件技术有限公 | 软件工程师

   工作描述：
   软件工程师主要负责特定模块的开发和维护工作

* 证书

    - 2002/01    中国计算机水平等级考试 高级程序员
    
* 教育经历
  
  - 1997/09-- 2001/07  XXXXXXX | XXXXXX | 本科

* 其他

   - 英语 ：读写能力良好 | 听说能力一般
